const { upsertJobs } = require('../upsertJobs');

const COURSES = [
  {
    external_id: 'coursera-dsa-ucsd',
    title: 'Data Structures and Algorithms Specialization',
    company: 'Coursera',
    role: 'Online Course',
    job_type: 'course',
    employment_type: 'any',
    domain: 'Backend',
    description: 'Master Algorithmic Programming Techniques. Learn algorithms through programming and advance your software engineering career.',
    branch_hint: ['CSE', 'DS'],
    skills_hint: ['data structures', 'algorithms', 'python', 'java'],
    location: 'Online',
    is_remote: true,
    country: 'India',
    salary_min: null,
    salary_max: null,
    salary_period: 'yearly',
    apply_url: 'https://www.coursera.org/specializations/data-structures-algorithms',
    posted_at: new Date(),
    deadline: null,
  },
  {
    external_id: 'coursera-ml-stanford',
    title: 'Machine Learning Specialization',
    company: 'Coursera (Stanford)',
    role: 'Online Course',
    job_type: 'course',
    employment_type: 'any',
    domain: 'AI / ML',
    description: 'Build ML models with NumPy and scikit-learn, build and train supervised models for prediction and binary classification tasks.',
    branch_hint: ['CSE', 'DS'],
    skills_hint: ['machine learning', 'python', 'tensorflow', 'deep learning'],
    location: 'Online',
    is_remote: true,
    country: 'India',
    salary_min: null,
    salary_max: null,
    salary_period: 'yearly',
    apply_url: 'https://www.coursera.org/specializations/machine-learning-introduction',
    posted_at: new Date(),
    deadline: null,
  },
  {
    external_id: 'udemy-web-bootcamp',
    title: 'The Complete Web Developer Bootcamp',
    company: 'Udemy',
    role: 'Online Course',
    job_type: 'course',
    employment_type: 'any',
    domain: 'Full Stack',
    description: 'Become a full-stack web developer. HTML, CSS, JavaScript, Node, React, MongoDB and more.',
    branch_hint: ['CSE'],
    skills_hint: ['javascript', 'react', 'nodejs', 'mongodb', 'html', 'css'],
    location: 'Online',
    is_remote: true,
    country: 'India',
    salary_min: null,
    salary_max: null,
    salary_period: 'yearly',
    apply_url: 'https://www.udemy.com/course/the-complete-web-development-bootcamp/',
    posted_at: new Date(),
    deadline: null,
  },
  {
    external_id: 'nptel-dbms',
    title: 'Database Management System',
    company: 'NPTEL (IIT Madras)',
    role: 'Online Course',
    job_type: 'course',
    employment_type: 'any',
    domain: 'Backend',
    description: 'Learn DBMS fundamentals including ER model, relational model, SQL, normalization, transactions and indexing.',
    branch_hint: ['CSE', 'ENTC'],
    skills_hint: ['sql', 'database', 'postgresql', 'mysql'],
    location: 'Online',
    is_remote: true,
    country: 'India',
    salary_min: null,
    salary_max: null,
    salary_period: 'yearly',
    apply_url: 'https://nptel.ac.in/courses/106106093',
    posted_at: new Date(),
    deadline: null,
  },
  {
    external_id: 'coursera-civil-bim',
    title: 'BIM Fundamentals for Engineers',
    company: 'Coursera (Autodesk)',
    role: 'Online Course',
    job_type: 'course',
    employment_type: 'any',
    domain: 'Civil / Structural',
    description: 'Understand how Building Information Modelling is used in civil engineering and construction.',
    branch_hint: ['CIVIL'],
    skills_hint: ['autocad', 'revit', 'bim'],
    location: 'Online',
    is_remote: true,
    country: 'India',
    salary_min: null,
    salary_max: null,
    salary_period: 'yearly',
    apply_url: 'https://www.coursera.org/learn/bim-fundamentals',
    posted_at: new Date(),
    deadline: null,
  },
  {
    external_id: 'coursera-embedded-systems',
    title: 'Introduction to Embedded Systems',
    company: 'Coursera (University of Colorado)',
    role: 'Online Course',
    job_type: 'course',
    employment_type: 'any',
    domain: 'Embedded / IoT',
    description: 'Learn embedded software and hardware interface design including C programming and microcontrollers.',
    branch_hint: ['ENTC', 'EE'],
    skills_hint: ['embedded c', 'arduino', 'microcontroller', 'iot'],
    location: 'Online',
    is_remote: true,
    country: 'India',
    salary_min: null,
    salary_max: null,
    salary_period: 'yearly',
    apply_url: 'https://www.coursera.org/specializations/introduction-embedded-systems',
    posted_at: new Date(),
    deadline: null,
  },
  {
    external_id: 'nptel-mech-cad',
    title: 'Computer Aided Engineering Design',
    company: 'NPTEL (IIT Bombay)',
    role: 'Online Course',
    job_type: 'course',
    employment_type: 'any',
    domain: 'Mechanical',
    description: 'CAD fundamentals for mechanical engineers: solid modeling, assembly, drafting using tools like SolidWorks and CATIA.',
    branch_hint: ['MECH'],
    skills_hint: ['solidworks', 'autocad', 'matlab', 'cad'],
    location: 'Online',
    is_remote: true,
    country: 'India',
    salary_min: null,
    salary_max: null,
    salary_period: 'yearly',
    apply_url: 'https://nptel.ac.in/courses/112101005',
    posted_at: new Date(),
    deadline: null,
  },
  {
    external_id: 'google-data-analytics',
    title: 'Google Data Analytics Professional Certificate',
    company: 'Coursera (Google)',
    role: 'Online Course',
    job_type: 'course',
    employment_type: 'any',
    domain: 'Data Science',
    description: 'Get job-ready for an entry-level data analytics role. Learn tools and platforms including spreadsheets, SQL, Tableau, and R.',
    branch_hint: ['CSE', 'DS'],
    skills_hint: ['sql', 'tableau', 'r programming', 'excel', 'python'],
    location: 'Online',
    is_remote: true,
    country: 'India',
    salary_min: null,
    salary_max: null,
    salary_period: 'yearly',
    apply_url: 'https://www.coursera.org/professional-certificates/google-data-analytics',
    posted_at: new Date(),
    deadline: null,
  },
];

const seedCourses = async () => {
  console.log('[seed:courses] Seeding ' + COURSES.length + ' curated courses...');
  await upsertJobs('coursera', COURSES);
  console.log('[seed:courses] Done');
};

module.exports = { seedCourses };